name: $(date:yyyyMMdd)$(rev:.rr)-$(BuildID)

resources:
  repositories:
  - repository: self
    clean: true
  - repository: v-davidcho/tools-agent-test
    clean: true
    name: v-davidcho/tools-agent-test
    type: git

 # - repository: SdkBuildScripts
 #   clean: true
 #   name: SdkBuildScripts
 #   type: git

trigger: none

# trigger:
#   branches:
#     include:
#     - main
#     - prerelease

extends:
  template: builds/azure-sphere-tools/templates/azure-sphere-tools.yml@SdkBuildScripts